version: '3'

services:
  web:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8098:80"
    volumes:
      - .:/srv
      - ./build/nginx/nginx-site.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: ./build/php
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/srv
    working_dir: /srv
    environment:
      APP_DATABASE_DSN: "postgres://app@postgres/app"
  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./var/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: app